/***********************************I-DAT-FEA-REC-1-27/01/2017****************************************/

INSERT INTO segu.tsubsistema ("codigo", "nombre", "fecha_reg", "prefijo", "estado_reg", "nombre_carpeta", "id_subsis_orig")
VALUES (E'REC', E'Gestion de Reclamos', E'2016-08-09', E'REC', E'activo', E'reclamo', NULL);

select pxp.f_insert_tgui ('<i class="fa fa-comments-o fa-2x"></i>GESTIÓN DE RECLAMOS', '', 'REC', 'si', 1, '', 1, '', '', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-compress  fa-2x"></i>Compensaciones', 'Compensacion', 'SISCOM', 'si', 3, 'sis_reclamo/vista/compensacion/Compensacion.php', 2, '', 'Compensacion', 'REC');
select pxp.f_insert_tgui ('Informes', 'Informe', 'SISINF', 'si', 2, 'sis_reclamo/vista/informe/Informe.php', 2, '', 'Informe', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-pinterest fa-2x"></i>Tipos de Incidentes', 'TipoIncidente', 'RECTI', 'si', 1, 'sis_reclamo/vista/tipo_incidente/TipoIncidente.php', 2, '', 'TipoIncidente', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-info-circle fa-2x"></i>Medios de Reclamo ', 'medio reclamo', 'MEDRE', 'si', 2, 'sis_reclamo/vista/medio_reclamo/MedioReclamo.php', 2, '', 'MedioReclamo', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-users fa-2x"></i>Clientes', 'Cliente Vista', 'CLI', 'si', 5, 'sis_reclamo/vista/cliente/Cliente.php', 2, '', 'Cliente', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-archive fa-2x"></i>Registro Reclamos', 'Reclamo', 'RECM', 'si', 1, 'sis_reclamo/vista/reclamo/RegistroReclamos.php', 2, '', 'RegistroReclamos', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-home fa-2x"></i>Catalogos', 'Catalogos', 'CAT', 'si', 1, '', 2, '', '', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-folder fa-2x"></i>Procesos', 'Procesos', 'PROC2', 'si', 2, '', 2, '', '', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-file-o fa-2x"></i>Reportes', 'Reportes', 'RE2', 'si', 3, '', 2, '', '', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-globe  fa-2x"></i>CRM Global', 'CRM Global', 'CRM', 'si', 2, 'sis_reclamo/vista/reporte/FormFiltros.php', 3, '', 'FormFiltros', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-folder-open fa-2x"></i>Consulta de Reclamos', 'Consulta de Reclamos', 'CONSREC', 'si', 7, 'sis_reclamo/vista/reclamo/ConsultaReclamo.php', 3, '', 'ConsultaReclamo', 'REC');
select pxp.f_insert_tgui ('<i class="fa  fa-ban fa-2x"></i>Motivos de Anulación', 'Motivos de Anulacion', 'MOTAN', 'si', 4, 'sis_reclamo/vista/motivo_anulado/MotivoAnulado.php', 3, '', 'MotivoAnulado', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-signal  fa-2x"></i>Reportes Estadisticos', 'Reportes Estadisticos', 'REPEST', 'si', 3, 'sis_reclamo/vista/reporte/ReportesEstadisticos.php', 3, '', 'ReportesEstadisticos', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'CLI.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 3, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'CLI.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'RECM.1', 'no', 0, 'sis_reclamo/vista/cliente/Cliente.php', 3, '', 'Cliente', 'REC');
select pxp.f_insert_tgui ('Informe', 'Informe', 'RECM.2', 'no', 0, 'sis_reclamo/vista/informe/Informe.php', 3, '', '50%', 'REC');
select pxp.f_insert_tgui ('Respuesta', 'Respuesta', 'RECM.3', 'no', 0, 'sis_reclamo/vista/respuesta/Respuesta.php', 3, '', '50%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECM.4', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 3, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECM.5', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 3, '', '../../sis_tesoreria/control/PlanPago/siguienteEstadoPlanPago', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'RECM.6', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 3, '', '80%', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'RECM.1.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 4, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'RECM.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 5, '', '50%', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'RECM.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 4, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'RECM.4.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'RECM.4.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 4, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'RECM.4.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 4, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'RECM.4.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'RECM.4.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 5, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECM.4.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'RECM.5.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'RECM.6.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 4, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'RECM.6.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 5, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'RECM.6.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 5, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECM.6.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 5, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'RECM.6.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 6, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECM.6.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 7, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'RECM.6.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 8, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'CONSREC.1', 'no', 0, 'sis_reclamo/vista/cliente/Cliente.php', 4, '', 'Cliente', 'REC');
select pxp.f_insert_tgui ('Informe', 'Informe', 'CONSREC.2', 'no', 0, 'sis_reclamo/vista/informe/Informe.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Respuesta', 'Respuesta', 'CONSREC.3', 'no', 0, 'sis_reclamo/vista/respuesta/Respuesta.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'CONSREC.4', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'CONSREC.5', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 4, '', '../../sis_tesoreria/control/PlanPago/siguienteEstadoPlanPago', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'CONSREC.6', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 4, '', '80%', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'CONSREC.1.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'CONSREC.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'CONSREC.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 5, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'CONSREC.4.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'CONSREC.4.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 5, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'CONSREC.4.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 5, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'CONSREC.4.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'CONSREC.4.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 6, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'CONSREC.4.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 7, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'CONSREC.5.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'CONSREC.6.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 5, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'CONSREC.6.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 6, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'CONSREC.6.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 6, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'CONSREC.6.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 6, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'CONSREC.6.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 7, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'CONSREC.6.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 8, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'CONSREC.6.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 9, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-list-ul fa-2x"></i>Revisión Reclamos', 'Revision', 'REVREC', 'si', 2, 'sis_reclamo/vista/reclamo/RevisionReclamo.php', 3, '', 'RevisionReclamo', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-history fa-2x"></i>Pendiente Respuesta', 'Pendiente', 'PENRES', 'si', 3, 'sis_reclamo/vista/reclamo/PendienteRespuesta.php', 3, '', 'PendienteRespuesta', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-openid fa-2x"></i>VoBo Respuesta', 'VoBo Respuesta', 'VBRES', 'si', 4, 'sis_reclamo/vista/respuesta/VoBoRespuesta.php', 3, '', 'VoBoRespuesta', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-legal fa-2x"></i>Reclamo Administrativo', 'Administrativo', 'RECADM', 'si', 6, 'sis_reclamo/vista/reclamo/ReclamoAdministrativo.php', 3, '', 'ReclamoAdministrativo', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECM.7', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 3, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'CONSREC.7', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 4, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'REVREC.1', 'no', 0, 'sis_reclamo/vista/cliente/Cliente.php', 4, '', 'Cliente', 'REC');
select pxp.f_insert_tgui ('Informe', 'Informe', 'REVREC.2', 'no', 0, 'sis_reclamo/vista/informe/Informe.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Respuesta', 'Respuesta', 'REVREC.3', 'no', 0, 'sis_reclamo/vista/respuesta/Respuesta.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'REVREC.4', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'REVREC.5', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 4, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'REVREC.6', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 4, '', '../../sis_tesoreria/control/PlanPago/siguienteEstadoPlanPago', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'REVREC.7', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 4, '', '80%', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'REVREC.1.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'REVREC.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'REVREC.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 5, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'REVREC.4.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'REVREC.4.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 5, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'REVREC.4.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 5, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'REVREC.4.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'REVREC.4.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 6, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'REVREC.4.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 7, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'REVREC.6.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'REVREC.7.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 5, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'REVREC.7.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 6, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'REVREC.7.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 6, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'REVREC.7.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 6, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'REVREC.7.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 7, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'REVREC.7.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 8, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'REVREC.7.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 9, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'PENRES.1', 'no', 0, 'sis_reclamo/vista/cliente/Cliente.php', 4, '', 'Cliente', 'REC');
select pxp.f_insert_tgui ('Informe', 'Informe', 'PENRES.2', 'no', 0, 'sis_reclamo/vista/informe/Informe.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Respuesta', 'Respuesta', 'PENRES.3', 'no', 0, 'sis_reclamo/vista/respuesta/Respuesta.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'PENRES.4', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'PENRES.5', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 4, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'PENRES.6', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 4, '', '../../sis_tesoreria/control/PlanPago/siguienteEstadoPlanPago', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'PENRES.7', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 4, '', '80%', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'PENRES.1.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'PENRES.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'PENRES.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 5, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'PENRES.4.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'PENRES.4.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 5, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'PENRES.4.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 5, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'PENRES.4.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'PENRES.4.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 6, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'PENRES.4.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 7, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'PENRES.6.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'PENRES.7.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 5, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'PENRES.7.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 6, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'PENRES.7.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 6, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'PENRES.7.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 6, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'PENRES.7.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 7, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'PENRES.7.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 8, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'PENRES.7.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 9, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'VBRES.1', 'no', 0, 'sis_reclamo/vista/cliente/Cliente.php', 4, '', 'Cliente', 'REC');
select pxp.f_insert_tgui ('Informe', 'Informe', 'VBRES.2', 'no', 0, 'sis_reclamo/vista/informe/Informe.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Respuesta', 'Respuesta', 'VBRES.3', 'no', 0, 'sis_reclamo/vista/respuesta/Respuesta.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'VBRES.4', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'VBRES.5', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 4, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'VBRES.6', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 4, '', '../../sis_tesoreria/control/PlanPago/siguienteEstadoPlanPago', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'VBRES.7', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 4, '', '80%', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'VBRES.1.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'VBRES.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'VBRES.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 5, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'VBRES.4.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'VBRES.4.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 5, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'VBRES.4.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 5, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'VBRES.4.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'VBRES.4.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 6, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'VBRES.4.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 7, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'VBRES.6.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'VBRES.7.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 5, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'VBRES.7.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 6, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'VBRES.7.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 6, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'VBRES.7.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 6, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'VBRES.7.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 7, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'VBRES.7.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 8, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'VBRES.7.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 9, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'RECADM.1', 'no', 0, 'sis_reclamo/vista/cliente/Cliente.php', 4, '', 'Cliente', 'REC');
select pxp.f_insert_tgui ('Informe', 'Informe', 'RECADM.2', 'no', 0, 'sis_reclamo/vista/informe/Informe.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Respuesta', 'Respuesta', 'RECADM.3', 'no', 0, 'sis_reclamo/vista/respuesta/Respuesta.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECADM.4', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECADM.5', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 4, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECADM.6', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 4, '', '../../sis_tesoreria/control/PlanPago/siguienteEstadoPlanPago', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'RECADM.7', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 4, '', '80%', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'RECADM.1.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'RECADM.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'RECADM.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 5, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'RECADM.4.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'RECADM.4.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 5, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'RECADM.4.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 5, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'RECADM.4.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'RECADM.4.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 6, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECADM.4.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 7, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'RECADM.6.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'RECADM.7.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 5, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'RECADM.7.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 6, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'RECADM.7.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 6, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECADM.7.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 6, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'RECADM.7.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 7, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECADM.7.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 8, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'RECADM.7.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 9, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('RespuestaDetalle', 'RespuestaDetalle', 'RECM.8', 'no', 0, 'sis_reclamo/vista/respuesta/RespuestaDetalle.php', 3, '', '50%', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'RECM.8.1', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 4, '', '80%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECM.8.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECM.8.3', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 4, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECM.8.4', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 4, '', 'FormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'RECM.8.1.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 5, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'RECM.8.1.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 6, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'RECM.8.1.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 6, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECM.8.1.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 6, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'RECM.8.1.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 7, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECM.8.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 8, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'RECM.8.1.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 9, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'RECM.8.2.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 5, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'RECM.8.2.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'RECM.8.2.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 5, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'RECM.8.2.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 5, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'RECM.8.2.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'RECM.8.2.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 6, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECM.8.2.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 7, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'RECM.8.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('RespuestaDetalle', 'RespuestaDetalle', 'CONSREC.8', 'no', 0, 'sis_reclamo/vista/respuesta/RespuestaDetalle.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'CONSREC.8.1', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 5, '', '80%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'CONSREC.8.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'CONSREC.8.3', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 5, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'CONSREC.8.4', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 5, '', 'FormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'CONSREC.8.1.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 6, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'CONSREC.8.1.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 7, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'CONSREC.8.1.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 7, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'CONSREC.8.1.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 7, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'CONSREC.8.1.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 8, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'CONSREC.8.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 9, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'CONSREC.8.1.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 10, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'CONSREC.8.2.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 6, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'CONSREC.8.2.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'CONSREC.8.2.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 6, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'CONSREC.8.2.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 6, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'CONSREC.8.2.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'CONSREC.8.2.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 7, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'CONSREC.8.2.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 8, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'CONSREC.8.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('RespuestaDetalle', 'RespuestaDetalle', 'REVREC.8', 'no', 0, 'sis_reclamo/vista/respuesta/RespuestaDetalle.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'REVREC.8.1', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 5, '', '80%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'REVREC.8.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'REVREC.8.3', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 5, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'REVREC.8.4', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 5, '', 'FormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'REVREC.8.1.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 6, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'REVREC.8.1.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 7, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'REVREC.8.1.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 7, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'REVREC.8.1.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 7, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'REVREC.8.1.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 8, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'REVREC.8.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 9, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'REVREC.8.1.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 10, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'REVREC.8.2.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 6, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'REVREC.8.2.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'REVREC.8.2.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 6, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'REVREC.8.2.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 6, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'REVREC.8.2.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'REVREC.8.2.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 7, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'REVREC.8.2.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 8, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'REVREC.8.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('RespuestaDetalle', 'RespuestaDetalle', 'PENRES.8', 'no', 0, 'sis_reclamo/vista/respuesta/RespuestaDetalle.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'PENRES.8.1', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 5, '', '80%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'PENRES.8.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'PENRES.8.3', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 5, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'PENRES.8.4', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 5, '', 'FormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'PENRES.8.1.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 6, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'PENRES.8.1.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 7, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'PENRES.8.1.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 7, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'PENRES.8.1.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 7, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'PENRES.8.1.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 8, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'PENRES.8.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 9, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'PENRES.8.1.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 10, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'PENRES.8.2.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 6, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'PENRES.8.2.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'PENRES.8.2.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 6, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'PENRES.8.2.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 6, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'PENRES.8.2.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'PENRES.8.2.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 7, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'PENRES.8.2.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 8, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'PENRES.8.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('RespuestaDetalle', 'RespuestaDetalle', 'RECADM.8', 'no', 0, 'sis_reclamo/vista/respuesta/RespuestaDetalle.php', 4, '', '50%', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'RECADM.8.1', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 5, '', '80%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECADM.8.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECADM.8.3', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 5, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RECADM.8.4', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 5, '', 'FormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'RECADM.8.1.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 6, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'RECADM.8.1.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 7, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'RECADM.8.1.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 7, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECADM.8.1.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 7, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'RECADM.8.1.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 8, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RECADM.8.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 9, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'RECADM.8.1.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 10, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'RECADM.8.2.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 6, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'RECADM.8.2.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'RECADM.8.2.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 6, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'RECADM.8.2.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 6, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'RECADM.8.2.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'RECADM.8.2.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 7, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RECADM.8.2.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 8, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'RECADM.8.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 6, '', '90%', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-clipboard fa-2x"></i>Libro de Reclamos', 'Libro de Reclamos', 'LIBREC', 'si', 1, 'sis_reclamo/vista/reporte/LibroReclamo.php', 3, '', 'LibroReclamo', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'RECM.9', 'no', 0, 'sis_reclamo/vista/cliente/FormCliente.php', 3, '', 'FormCliente', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'RECM.9.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 4, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'RECM.9.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 5, '', '50%', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'CONSREC.9', 'no', 0, 'sis_reclamo/vista/cliente/FormCliente.php', 4, '', 'FormCliente', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'CONSREC.9.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'CONSREC.9.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'REVREC.9', 'no', 0, 'sis_reclamo/vista/cliente/FormCliente.php', 4, '', 'FormCliente', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'REVREC.9.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'REVREC.9.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'PENRES.9', 'no', 0, 'sis_reclamo/vista/cliente/FormCliente.php', 4, '', 'FormCliente', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'PENRES.9.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'PENRES.9.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'RECADM.9', 'no', 0, 'sis_reclamo/vista/cliente/FormCliente.php', 4, '', 'FormCliente', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'RECADM.9.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 5, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'RECADM.9.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 6, '', '50%', 'REC');
select pxp.f_insert_tgui ('Detalle Filtro', 'Detalle Filtro', 'CRM.1', 'no', 0, 'sis_reclamo/vista/reporte/CRMGlobal.php', 4, '', '70%', 'REC');
select pxp.f_insert_tgui ('Clientes', 'Clientes', 'CRM.1.1', 'no', 0, 'sis_reclamo/vista/cliente/FormCliente.php', 5, '', 'FormCliente', 'REC');
select pxp.f_insert_tgui ('Lugar', 'Lugar', 'CRM.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/Lugar.php', 6, '', 'Lugar', 'REC');
select pxp.f_insert_tgui ('Ubicacion Lugar', 'Ubicacion Lugar', 'CRM.1.1.1.1', 'no', 0, 'sis_parametros/vista/lugar/mapaLugar.php', 7, '', '50%', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-legal fa-2x"></i>Revision Legal', 'Revision Legal', 'RL', 'si', 5, 'sis_reclamo/vista/respuesta/RevisionLegal.php', 3, '', 'RevisionLegal', 'REC');
select pxp.f_insert_tgui ('Elija Opcion de Reporte', 'Elija Opcion de Reporte', 'REPEST.1', 'no', 0, 'west', 4, '', 'padding:5px 5px 0', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'REPEST.2', 'no', 0, 'sis_parametros/vista/widget/WidgetDash.php', 4, '', '70%', 'REC');
select pxp.f_insert_tgui ('Observaciones del WF', 'Observaciones del WF', 'RL.1', 'no', 0, 'sis_workflow/vista/obs/Obs.php', 4, '', '80%', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RL.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 4, '', '90%', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RL.3', 'no', 0, 'sis_workflow/vista/estado_wf/AntFormEstadoWf.php', 4, '', 'AntFormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Estado de Wf', 'Estado de Wf', 'RL.4', 'no', 0, 'sis_workflow/vista/estado_wf/FormEstadoWf.php', 4, '', 'FormEstadoWf', 'REC');
select pxp.f_insert_tgui ('Funcionarios', 'Funcionarios', 'RL.1.1', 'no', 0, 'sis_organigrama/vista/funcionario/Funcionario.php', 5, '', 'funcionario', 'REC');
select pxp.f_insert_tgui ('Cuenta Bancaria del Empleado', 'Cuenta Bancaria del Empleado', 'RL.1.1.1', 'no', 0, 'sis_organigrama/vista/funcionario_cuenta_bancaria/FuncionarioCuentaBancaria.php', 6, '', 'FuncionarioCuentaBancaria', 'REC');
select pxp.f_insert_tgui ('Especialidad del Empleado', 'Especialidad del Empleado', 'RL.1.1.2', 'no', 0, 'sis_organigrama/vista/funcionario_especialidad/FuncionarioEspecialidad.php', 6, '', 'FuncionarioEspecialidad', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RL.1.1.3', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 6, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Instituciones', 'Instituciones', 'RL.1.1.1.1', 'no', 0, 'sis_parametros/vista/institucion/Institucion.php', 7, '', 'Institucion', 'REC');
select pxp.f_insert_tgui ('Personas', 'Personas', 'RL.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/Persona.php', 8, '', 'persona', 'REC');
select pxp.f_insert_tgui ('Subir foto', 'Subir foto', 'RL.1.1.1.1.1.1', 'no', 0, 'sis_seguridad/vista/persona/subirFotoPersona.php', 9, '', 'subirFotoPersona', 'REC');
select pxp.f_insert_tgui ('Subir ', 'Subir ', 'RL.2.1', 'no', 0, 'sis_workflow/vista/documento_wf/SubirArchivoWf.php', 5, '', 'SubirArchivoWf', 'REC');
select pxp.f_insert_tgui ('Documentos de Origen', 'Documentos de Origen', 'RL.2.2', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('Histórico', 'Histórico', 'RL.2.3', 'no', 0, 'sis_workflow/vista/documento_historico_wf/DocumentoHistoricoWf.php', 5, '', '30%', 'REC');
select pxp.f_insert_tgui ('Estados por momento', 'Estados por momento', 'RL.2.4', 'no', 0, 'sis_workflow/vista/tipo_documento_estado/TipoDocumentoEstadoWF.php', 5, '', '40%', 'REC');
select pxp.f_insert_tgui ('Pagos similares', 'Pagos similares', 'RL.2.5', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepFilPlanPago.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('73%', '73%', 'RL.2.5.1', 'no', 0, 'sis_tesoreria/vista/plan_pago/RepPlanPago.php', 6, '', 'RepPlanPago', 'REC');
select pxp.f_insert_tgui ('Chequear documento del WF', 'Chequear documento del WF', 'RL.2.5.1.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 7, '', '90%', 'REC');
select pxp.f_insert_tgui ('Documentos del Proceso', 'Documentos del Proceso', 'RL.4.1', 'no', 0, 'sis_workflow/vista/documento_wf/DocumentoWf.php', 5, '', '90%', 'REC');
select pxp.f_insert_tgui ('<i class="fa fa-clipboard fa-2x"></i>Libro de Respuestas', 'Libro de Respuestas', 'LIBRES', 'si', 4, 'sis_reclamo/vista/reporte/LibroRespuesta.php', 3, '', 'LibroRespuesta', 'REC');

/***********************************F-DAT-FEA-REC-1-27/01/2017****************************************/

